account/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from .views import superuser, del_user, edit_user
from .views import logout, Login, Signup, ForgetPassword, Activate, ConsolidatedView

urlpatterns = [
    path('login', Login.as_view(), name='login'),
    path('signup', Signup.as_view(), name='signup'),
    path('logout', login_required(logout), name='logout'),
    path('activate/<uidb64>/<token>/', Activate.as_view(), name='activate'),
    path('forget-password/<uidb64>/<token>', ForgetPassword.as_view(), name='forget_password'),

    path('superuser/', login_required(superuser), name='superuser'),
    path('edit_user/<username>', login_required(edit_user), name='edit_user'),
    path('delete-user/<username>', login_required(del_user), name='delete_user'),

    path('consolidated-view-all', login_required(ConsolidatedView.as_view()), name='consolidated_view_all'),
    path('consolidated-view-c_o_e/<c_o_e>', login_required(ConsolidatedView.as_view()), name='consolidated_c_o_e'),
    path('consolidated-view-username/<username>', login_required(ConsolidatedView.as_view()), name='consolidated_username'),
]

cbseevents/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path

from .views import *

admin.site.site_header = settings.ADMIN_SITE_HEADER
admin.site.site_title = settings.ADMIN_SITE_TITLE

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('event/', include(('event.urls', 'event'), namespace='event')),
    path('account/', include(('account.urls', 'account'), namespace='account')),
    path('registration/', include(('registration.urls', 'registration'), namespace='registration')),

    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),

    # path('set', set_user),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

event/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from .views import AddEvent, EventDetail, UpdateEvent, DeleteEvent, EventListView

urlpatterns = [
    path('', EventListView.as_view(), name='event_list'),
    path('add-event', login_required(AddEvent.as_view()), name='add_event'),
    path('<slug>/event-detail', EventDetail.as_view(), name='event_detail'),
    path('<slug>/update-event', login_required(UpdateEvent.as_view()), name='update_event'),
    path('<slug>/delete/<timestamp>', login_required(DeleteEvent.as_view()), name='delete_event'),
]

registration/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from .views import RegisterEvent, RegistrationDetail, RegisterStudentList
from .views import EnrollmentReport, RegistrationReport, TransactionReport

urlpatterns = [
    path('<slug>/register-event', login_required(RegisterEvent.as_view()), name='register_event'),
    path('<slug>/student-list', login_required(RegisterStudentList.as_view()), name='register_student_list'),
    path('<registration_id>/detail', login_required(RegistrationDetail.as_view()), name='registration_detail'),
    path('<slug>/print-enroll-list', login_required(EnrollmentReport.as_view()), name='print_enroll_list'),
    path('<slug>/print-student-list', login_required(RegistrationReport.as_view()), name='print_student_list'),
    path('<slug>/print-transaction-list', login_required(TransactionReport.as_view()), name='print_transaction_list'),
]

account/models.py
from django.db import models

# Create your models here.

account/views.py
import json
import urllib.parse
import urllib.request
from datetime import date

from django.conf import settings
from django.contrib import messages, auth
from django.contrib.auth.models import User
from django.contrib.sites.shortcuts import get_current_site
from django.core.exceptions import PermissionDenied, ObjectDoesNotExist
from django.core.mail import EmailMessage
from django.shortcuts import render, redirect
from django.template.loader import render_to_string
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.views.generic import TemplateView

from event.models import EventRecord
from registration.models import RegistrationRecord
from student.forms import StudentForm
from student.models import StudentRecord
from .forms import SignupForm, LoginForm, ResetPasswordForm, EditUserForm, EmailForm
from .tokens import account_activation_token, password_reset_token


# Create your views here.
def is_block(request, user):
    if not user.is_active and user.last_login:
        return True
    return False


def logout(request):
    auth.logout(request)
    return redirect('home')


# noinspection PyBroadException
class Login(TemplateView):
    template = 'login.html'

    def get(self, request, *args, **kwargs):
        form = LoginForm()
        form1 = EmailForm()
        request.session['head_name'] = 'login'
        return render(request, self.template, {'form': form, 'form1': form1, 'site_key': settings.RECAPTCHA_SITE_KEY})

    def post(self, request):
        try:
            form = LoginForm(request.POST)
            form1 = EmailForm(request.POST)
            ''' Begin reCAPTCHA validation '''
            values = {
                'secret': settings.RECAPTCHA_PRIVATE_KEY,
                'response': request.POST.get('recaptcha')
            }
            data = urllib.parse.urlencode(values).encode()
            req = urllib.request.Request(settings.RECAPTCHA_SITE_VERIFICATION_URL, data=data)
            response = urllib.request.urlopen(req)
            result = json.loads(response.read().decode())
            # print(result)
            ''' End reCAPTCHA validation '''

            # Login Form
            if result['success'] and result['action'] == 'login' and form.is_valid():
                email = form.cleaned_data['email']
                password = form.cleaned_data['password']
                u = User.objects.get(username=email.lower())
                if is_block(request, u):
                    raise PermissionDenied('Your Account is blocked. Please Contact Us')

                user = auth.authenticate(username=email.lower(), password=password)
                if user is not None:
                    auth.login(request, user)
                    if 'next' in request.POST:
                        return redirect(request.POST.get('next'))
                    return redirect("account:consolidated_view_all")
                elif not u.is_active:
                    messages.warning(request, 'Please confirm the activation link from your Email')
                else:
                    messages.error(request, "Your authentication information is incorrect. Please try again.")

            # Forget Password
            elif result['success'] and result['action'] == 'forgetPassword' and form1.is_valid():
                email = form1.cleaned_data['email1']
                user = User.objects.get(username=email.lower())
                if is_block(request, user):
                    raise PermissionDenied('Your Account is blocked. Please Contact Us')

                '''Begin Email Sending '''
                current_site = get_current_site(request)
                mail_subject = 'Password Reset link of your CBSE Account.'
                message = render_to_string('forget-password.txt', {
                    'user': user,
                    'domain': current_site.domain,
                    'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                    'token': password_reset_token.make_token(user),
                    'email': settings.CONTACT_EMAIL,
                    'number': settings.CONTACT_NUMBER
                })
                email = EmailMessage(mail_subject, message, to=[user.email])
                email.send()
                '''End Email sending'''

                messages.success(request, 'Password reset link has been sent to your registered E-mail Address')
                return redirect('home')
            else:
                messages.warning(request, 'Invalid Input or Invalid reCAPTCHA. Please try again')

        except ObjectDoesNotExist:
            messages.error(request, 'Invalid Inputs. Please try again')
        except PermissionDenied as e:
            messages.error(request, e)
            return redirect('home')
        except Exception as e:
            messages.error(request, (str(e) + '. Please Contact Us'))
        form = LoginForm()
        form1 = EmailForm()
        return render(request, self.template, {'form': form, 'form1': form1, 'site_key': settings.RECAPTCHA_SITE_KEY})


# noinspection PyBroadException
class Signup(TemplateView):
    template_name = 'signup.html'

    def get(self, request, *args, **kwargs):
        form = SignupForm()
        request.session['head_name'] = 'signup'
        return render(request, self.template_name, {'form1': form, 'site_key': settings.RECAPTCHA_SITE_KEY})

    def post(self, request):
        try:
            ''' Begin reCAPTCHA validation '''
            values = {
                'secret': settings.RECAPTCHA_PRIVATE_KEY,
                'response': request.POST.get('recaptcha')
            }
            data = urllib.parse.urlencode(values).encode()
            req = urllib.request.Request(settings.RECAPTCHA_SITE_VERIFICATION_URL, data=data)
            response = urllib.request.urlopen(req)
            result = json.loads(response.read().decode())
            # print(result)
            ''' End reCAPTCHA validation '''

            form = SignupForm(request.POST)
            if result['success'] and result['action'] == 'signup' and form.is_valid():
                first_name = form.cleaned_data['first_name']
                last_name = form.cleaned_data['last_name']
                email = form.cleaned_data['email'].lower()
                password = form.cleaned_data['password']
                try:
                    user = User.objects.get(username=email)
                    if is_block(request, user):
                        raise PermissionDenied('Your Account is blocked. Please Contact Us')
                    user.first_name = first_name
                    user.last_name = last_name
                    user.set_password(password)
                    user.save()
                except ObjectDoesNotExist:
                    user = User.objects.create(username=email, email=email, password=password, first_name=first_name,
                                               last_name=last_name, is_active=False)

                '''Begin Email Sending '''
                current_site = get_current_site(request)
                mail_subject = 'Action Required: Activate your CBSE account'
                message = render_to_string('acc_active_email.txt', {
                    'user': user,
                    'domain': current_site.domain,
                    'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                    'token': account_activation_token.make_token(user),
                    'email': settings.CONTACT_EMAIL,
                    'number': settings.CONTACT_NUMBER
                })
                email = EmailMessage(mail_subject, message, to=[user.email])
                email.send()
                '''End Email sending'''

                messages.success(request, 'Check your mail to complete registration')
                return redirect("account:login")
            else:
                messages.warning(request, 'Invalid Input or Invalid reCAPTCHA. Please try again')
            return render(request, self.template_name, {'form1': form, 'site_key': settings.RECAPTCHA_SITE_KEY})

        except PermissionDenied as e:
            messages.error(request, e)
            return redirect('home')
        except Exception as e:
            messages.error(request, (str(e) + '. Please Contact Us'))
            return redirect("account:signup")


# noinspection PyBroadException
class Activate(TemplateView):
    template_name = 'activate.html'

    def get(self, request, *args, **kwargs):
        try:
            uid = force_text(urlsafe_base64_decode(kwargs['uidb64']))
            user = User.objects.get(pk=uid)
            if account_activation_token.check_token(user, kwargs['token']):
                if is_block(request, user):
                    raise PermissionDenied('Your Account is blocked. Please Contact Us')

                form = StudentForm()
                return render(request, self.template_name, {'user': user, 'form': form})
            else:
                raise PermissionDenied('Activation link is invalid! Please SignUp Again or Contact Us')

        except PermissionDenied as e:
            messages.error(request, e)
            return redirect('home')
        except Exception as e:
            messages.error(request, (str(e) + '. Please Contact Us'))
            return redirect("account:signup")

    def post(self, request, **kwargs):
        try:
            uid = force_text(urlsafe_base64_decode(kwargs['uidb64']))
            user = User.objects.get(pk=uid)
            if account_activation_token.check_token(user, kwargs['token']):
                if is_block(request, user):
                    raise PermissionDenied('Your Account is blocked. Please Contact Us')

                form = StudentForm(request.POST)
                if form.is_valid():
                    temp = form.save(commit=False)
                    temp.user = user
                    temp.save()

account/templates/activate.html
{% extends "base.html" %}{% block head_title %}Account Activation | {{ block.super }}{% endblock %}{% block content %}
    <main role="main" class="container col-xl-4 col-lg-5 col-md-6 p-4 mt-md-4 mt-2 mb-5" style="background-color: #f7f5f5;box-shadow: 0 0 5px 5px #d4d2cf;border-radius: 5px">
        <h3 class="text-center pb-3">Fill your Personal Detail</h3>
        <form method="post">{% csrf_token %}
            <div class="row">
                <div class="col-md-6 mb-4">
                    <label for="first_name">First Name</label><input id="first_name" type="text" class="form-control" value="{{ user.first_name }}" disabled>
                </div>
                <div class="col-md-6 mb-4">
                    <label for="last_name">Last Name</label><input id="last_name" type="text" class="form-control" value="{{ user.last_name }}" disabled>
                </div>
            </div>
            <div class="mb-4">
                <label for="email">Email</label><input id="email" type="email" class="form-control" value="{{ user.email }}" disabled>
            </div>
            <div class="row">
                <div class="col-md-6 mb-4">
                    <label>Admission Number</label>{{ form.roll_no }}<span style="color:red;">{{ form.roll_no.errors }}</span>
                </div>
                <div class="col-md-6 mb-4">
                    <label>Phone Number</label>{{ form.number }}<span style="color:red;">{{ form.number.errors }}</span>
                </div>
            </div>
            <div class="mb-4"><label>College Name</label>{{ form.college_name }}</div>
            <div class="row">
                <div class="col-md-4 mb-4"><label>Branch</label>{{ form.branch }}</div>
                <div class="col-md-4 mb-4"><label>Batch Start</label>{{ form.batch_start }}</div>
                <div class="col-md-4 mb-4"><label>Batch End</label>{{ form.batch_end }}</div>
            </div>
            <button type="submit" class="btn btn-success btn-block mb-4">Activate Account</button>
            <a href="{% url 'home' %}" class="btn btn-outline-danger btn-block">Go to Home Page</a>
        </form>
    </main>{% endblock %}{% block script %}{% endblock %}

account/templates/consolidated_view.html
{% extends "base.html" %}{% load staticfiles %}{% block head_title %}Consolidated View | {{ block.super }}{% endblock %}
{% block css %}{% endblock %}{% block content %}
    <main role="main" class="container p-4 mt-md-4 mt-2 mb-5">{% if user.is_superuser %}
        <div class="pb-4">Center of Excellence:
            <a href="{% url 'account:consolidated_view_all' %}" class="btn btn-sm btn-outline-primary m-2" style="min-width: 50px;" title="All Event">All</a>
            <a href="{% url 'account:consolidated_c_o_e' c_o_e='SDA' %}" class="btn btn-sm btn-outline-primary m-2" style="min-width: 50px;" title="Structural Design And Analysis">SDA</a>
            <a href="{% url 'account:consolidated_c_o_e' c_o_e='NW' %}" class="btn btn-sm btn-outline-primary m-2" style="min-width: 50px;" title="Cisco Networking Academy">NW</a>
            <a href="{% url 'account:consolidated_c_o_e' c_o_e='TIES' %}" class="btn btn-sm btn-outline-primary m-2" style="min-width: 50px;" title="Texas Instruments Embedded System Lab">TIES</a>
            <a href="{% url 'account:consolidated_c_o_e' c_o_e='SMC' %}" class="btn btn-sm btn-outline-primary m-2" style="min-width: 50px;" title="SMC India Pvt Ltd.">SMC</a>
            <a href="{% url 'account:consolidated_c_o_e' c_o_e='IARTC' %}" class="btn btn-sm btn-outline-primary m-2" style="min-width: 50px;" title="Industrial Automation Research And Training Centre">IARTC</a>
            <a href="{% url 'account:consolidated_c_o_e' c_o_e='VLSI' %}" class="btn btn-sm btn-outline-primary m-2" style="min-width: 50px;" title="VLSI Design">VLSI</a>
            <a href="{% url 'account:consolidated_c_o_e' c_o_e='BIGD' %}" class="btn btn-sm btn-outline-primary m-2" style="min-width: 50px;" title="Big Data Analytics">BIGD</a>
            <a href="{% url 'account:consolidated_c_o_e' c_o_e='MobApp' %}" class="btn btn-sm btn-outline-primary m-2" style="min-width: 50px;" title="Mobile Application Development">MobApp</a>
            <a href="{% url 'account:consolidated_c_o_e' c_o_e='SWD' %}" class="btn btn-sm btn-outline-primary m-2" style="min-width: 50px;" title="Center For Enterprise Software Development">SWD</a>
            <a href="{% url 'account:consolidated_c_o_e' c_o_e='TST' %}" class="btn btn-sm btn-outline-primary m-2" style="min-width: 50px;" title="Testing">TST</a>
            <a href="{% url 'account:consolidated_c_o_e' c_o_e='NI' %}" class="btn btn-sm btn-outline-primary m-2" style="min-width: 50px;" title="ABES-NI Innovation Centre">NI</a>
        </div>{% endif %}
        <div class="card-deck my-4">{% if user.is_staff or user.is_superuser %}{% for event in event_list %}
            <div class="card mb-4 shadow-sm">
                <div class="card-header btn-toolbar justify-content-between">
                    <span class="font-weight-normal text-capitalize">{{ event.type }}</span>
                    {% if now <= event.registration_end %}<span class="text-success">Active</span>
                    {% else %}<span class="text-danger">Not Active</span>{% endif %}
                </div>
                <div class="card-body">
                    <p>Event Name:
                        <a href="{% url 'event:event_detail' event.slug %}">{{ event.event_name }}</a><br> Event Code:
                        <a href="{% url 'event:event_detail' event.slug %}">{{ event }}</a><br> Event Date:
                        <span class="text-danger">{{ event.event_date|date:"F d, Y" }}</span><br>Trainer:
                        {% if user.is_superuser %}<a href="{% url 'account:consolidated_username' event.user %}">
                        {% endif %}{{ event.user.first_name }} {{ event.user.last_name }}</a></p>
                    <p>No. of Student Registered {{ event.registered_student }}</p>
                    <div class="pt-2 btn-toolbar justify-content-between">
                        <a href="{% url 'registration:register_student_list' event.slug %}">Student List</a>
                        <a href="{% url 'registration:print_student_list' event.slug %}">Registration Report</a>
                    </div>
                    <div class="pt-2 btn-toolbar justify-content-between">
                        <a href="{% url 'registration:print_transaction_list' event.slug %}">Transaction Report</a>
                        <a href="{% url 'registration:print_enroll_list' event.slug %}">Enrollment Report</a>
                    </div>
                </div>
                <hr>
                <div class="pb-3 px-3 btn-toolbar justify-content-between">
                    <a href="{% url 'event:update_event' slug=event.slug %}" class="btn btn-outline-primary btn-sm px-4">Update</a>
                    <a href="{% url 'event:delete_event' slug=event.slug timestamp=event.timestamp %}" class="btn btn-outline-danger btn-sm px-4" onclick="return confirm('Are you sure to Delete {{ event.event_name }} event?')">Delete</a>
                </div>
            </div>{% endfor %}{% if not event_list %}
            <span class="text-danger">No Event Yet. Please create a Event</span>{% endif %}{% else %}
            {% for reg in event_list %}
                <div class="card mb-4 shadow-sm">
                    <div class="card-header btn-toolbar justify-content-between">
                        <span class="font-weight-normal text-capitalize">{{ reg.event.type }}</span>
                        {% if now <= reg.event.registration_end %}<span class="text-success">Active</span>
                        {% else %}<span class="text-danger">Not Active</span>{% endif %}
                    </div>
                    <div class="card-body">
                        <p>Event Name: <a href="{% url 'event:event_detail' reg.event %}">{{ reg.event.event_name }}</a><br> Event Code:
                            <a href="{% url 'event:event_detail' reg.event %}">{{ reg.event }}</a><br> Event Date:
                            <span class="text-danger">{{ reg.event.event_date|date:"F d, Y" }}</span><br> Trainer: {{ reg.event.user.first_name }} {{ reg.event.user.last_name }}
                        </p>
                    </div>
                    <hr>
                    <div class="pb-3 px-3 btn-toolbar justify-content-between">
                        <a href="{% url 'event:event_detail' reg.event %}" class="btn btn-outline-primary btn-sm px-4">Detail</a>
                        <a href="" class="btn btn-outline-danger btn-sm px-4">Feedback</a>
                    </div>
                </div>{% endfor %}{% endif %}
        </div>
    </main>
{% endblock %}{% block script %}{% endblock %}

account/templates/edit_user.html
{% extends "base.html" %}{% load staticfiles %}{% block head_title %}Update Account | {{ block.super }}{% endblock %}
{% block css %}{% endblock %}
{% block content %}
    <main role="main" class="container col-md-6 bg-white">
        <div class="px-md-3 px-2 pt-4 pb-5">
            <div style="text-align: center">
                <h3>Update Account</h3>
            </div>
            <form action="" method="post" class="px-md-2">{% csrf_token %}
                <div class="mb-3">
                    <label>Email</label>{{ form.email }}{{ form.email.errors }}
                </div>
                <div class="row">
                    <div class="col-md-6 mb-3">
                        <label>First Name</label>{{ form.first_name }}{{ form.first_name.errors }}
                    </div>
                    <div class="col-md-6 mb-3">
                        <label>Last Name</label>{{ form.last_name }}{{ form.last_name.errors }}
                    </div>
                </div>
                <div class="mb-3">
                    <label>Password</label>{{ form.password }}{{ form.password.errors }}</div>
                <div class="mb-3" style="font-size: 14px">
                    <li>Use at least one lowercase and uppercase letter, one numeral, one symbol and 8 character
                    </li>
                    <li>Your password can&#39;t be a commonly used password.</li>
                    <li>Your password can&#39;t be entirely numeric.</li>
                    <li>Your password can&#39;t be too similar to your other personal information.</li>
                </div>
                <div class="mb-3">
                    <label>Confirm Password</label>{{ form.confirm_password }}{{ form.confirm_password.errors }}
                </div>
                <div class="py-2 clearfix">
                    <button type="submit" class="btn btn-outline-success btn-block mb-2">Submit</button>
                    <button type="reset" class="btn btn-outline-danger btn-block mb-2">Reset</button>
                </div>
            </form>
        </div>
    </main>
{% endblock %}

account/templates/superuser.html
{% extends "base.html" %}{% load staticfiles %}{% block head_title %}User | {{ block.super }}{% endblock %}
{% block css %}{% endblock %}{% block content %}{% if user.is_superuser %}
    <div class="bg-white pb-4 px-md-5 px-2 rounded shadow-sm">
        <div class="pt-4 d-flex justify-content-between"><h2>List of User</h2>
            <div style="width: 300px">
                <input type="text" class="form-control" id="search" onkeyup="mySearch123()" placeholder="Search...">
            </div>
        </div>
        <div class="py-3 pb-2 table-responsive-xl">{% if u %}
            <table class="table table-bordered table-hover" id="myTable">
                <thead>
                <tr style="font-weight: 600;">
                    <th scope="col" width="5%">#</th>
                    <th scope="col">Name</th>
                    <th scope="col">Email</th>
                    <th scope="col" width="10%" style="text-align: center; vertical-align: middle;">Detail</th>
                    <th scope="col" width="10%" style="text-align: center; vertical-align: middle;">Edit</th>
                    <th scope="col" width="10%" style="text-align: center; vertical-align: middle;">Delete</th>
                </tr>
                </thead>
                <tbody>{% for i in u %}
                    <tr>
                        <td scope="row">{{ forloop.counter }}</td>
                        <td>{{ i.first_name }} {{ i.last_name }}</td>
                        <td>{{ i.email }}</td>
                        <td style="text-align: center; vertical-align: middle;">
                            <a href="{% url 'account:consolidated_username' username=i %}">
                                <img src="{% static 'images/icons8-profile.png' %}" alt="Profile"></a></td>
                        <td style="text-align: center; vertical-align: middle;">
                            <a href="{% url 'account:edit_user' username=i %}">
                                <img src="{% static 'images/icons8-edit.png' %}" alt=""></a></td>
                        <td style="text-align: center; vertical-align: middle;">
                            <a href="{% url 'account:delete_user' username=i %}">
                                <img src="{% static 'images/icons8-cancel.png' %}" alt="&times;"></a>
                    </tr>{% endfor %}</tbody>
            </table>{% else %}
            <h3>No User yet</h3>{% endif %}</div>
        <div class="clearfix">
            <button class="btn btn-sm btn-outline-info" style="width:150px;" data-toggle="modal"
                    data-target="#myModal">Add User
            </button>
        </div>
    </div>
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
         aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title" id="myModalLabel">Add User</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
                </div>
                <div class="modal-body">
                    <form action="" method="post" class="px-md-2">{% csrf_token %}
                        <div class="mb-3">
                            <label>Email</label>{{ form.email }}{{ form.email.errors }}
                        </div>
                        <div class="row">
                            <div class="col-md-6 mb-3">
                                <label>First Name</label>{{ form.first_name }}{{ form.first_name.errors }}
                            </div>
                            <div class="col-md-6 mb-3">
                                <label>Last Name</label>{{ form.last_name }}{{ form.last_name.errors }}
                            </div>
                        </div>
                        <div class="mb-3">
                            <label>Password</label>{{ form.password }}{{ form.password.errors }}</div>
                        <div class="mb-3" style="font-size: 14px">
                            <li>Use at least one lowercase and uppercase letter, one numeral, one symbol and 8 character
                            </li>
                            <li>Your password can&#39;t be a commonly used password.</li>
                            <li>Your password can&#39;t be entirely numeric.</li>
                            <li>Your password can&#39;t be too similar to your other personal information.</li>
                        </div>
                        <div class="mb-3">
                            <label>Confirm Password</label>{{ form.confirm_password }}{{ form.confirm_password.errors }}
                        </div>
                        <div class="py-2 clearfix">
                            <button type="submit" class="btn btn-outline-success btn-block mb-2">Submit</button>
                            <button type="reset" class="btn btn-outline-danger btn-block mb-2">Reset</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>{% endif %}
{% endblock %}
{% block script %}
    <script>
        function mySearch123() {
            let input, filter, table, tr, td1, td2, td3, i;
            input = document.getElementById("search");
            filter = input.value.toUpperCase();
            table = document.getElementById("myTable");
            tr = table.getElementsByTagName("tr");
            for (i = 0; i < tr.length; i++) {
                td1 = tr[i].getElementsByTagName("td")[1];
                td2 = tr[i].getElementsByTagName("td")[2];
                td3 = tr[i].getElementsByTagName("td")[3];
                if (td1 || td2 || td3) {
                    if ((td1.innerHTML.toUpperCase().indexOf(filter) > -1) ||
                        (td2.innerHTML.toUpperCase().indexOf(filter) > -1) ||
                        (td3.innerHTML.toUpperCase().indexOf(filter) > -1)) {
                        tr[i].style.display = "";
                    } else {
                        tr[i].style.display = "none";
                    }
                }
            }
        }
    </script>{% endblock %}