cbseevents/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path

from .views import *

admin.site.site_header = settings.ADMIN_SITE_HEADER
admin.site.site_title = settings.ADMIN_SITE_TITLE

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('event/', include(('event.urls', 'event'), namespace='event')),
    path('account/', include(('account.urls', 'account'), namespace='account')),
    path('registration/', include(('registration.urls', 'registration'), namespace='registration')),

    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),

    # path('set', set_user),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

event/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from .views import AddEvent, EventDetail, UpdateEvent, DeleteEvent, EventListView

urlpatterns = [
    path('', EventListView.as_view(), name='event_list'),
    path('add-event', login_required(AddEvent.as_view()), name='add_event'),
    path('<slug>/event-detail', EventDetail.as_view(), name='event_detail'),
    path('<slug>/update-event', login_required(UpdateEvent.as_view()), name='update_event'),
    path('<slug>/delete/<timestamp>', login_required(DeleteEvent.as_view()), name='delete_event'),
]

registration/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from .views import RegisterEvent, RegistrationDetail, RegisterStudentList
from .views import EnrollmentReport, RegistrationReport, TransactionReport

urlpatterns = [
    path('<slug>/register-event', login_required(RegisterEvent.as_view()), name='register_event'),
    path('<slug>/student-list', login_required(RegisterStudentList.as_view()), name='register_student_list'),
    path('<registration_id>/detail', login_required(RegistrationDetail.as_view()), name='registration_detail'),
    path('<slug>/print-enroll-list', login_required(EnrollmentReport.as_view()), name='print_enroll_list'),
    path('<slug>/print-student-list', login_required(RegistrationReport.as_view()), name='print_student_list'),
    path('<slug>/print-transaction-list', login_required(TransactionReport.as_view()), name='print_transaction_list'),
]

event/models.py
from django.contrib.auth.models import User
from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField

from .utils import get_unique_slug


# Create your models here.
class EventRecord(models.Model):
    slug = models.SlugField(unique=True)
    type = models.CharField(max_length=50)
    c_o_e = models.CharField(max_length=75)

    event_name = models.CharField(max_length=110)
    event_pic = models.FileField(default='')
    fees = models.FloatField()
    registration_start = models.DateField()
    registration_end = models.DateField()
    event_date = models.DateField()
    duration_number = models.CharField(max_length=10)
    duration_string = models.CharField(max_length=10)
    eligible_branches = models.CharField(max_length=100)
    eligible_year = models.CharField(max_length=100)

    pre_requisites_1 = models.CharField(max_length=50, default='')
    pre_requisites_2 = models.CharField(max_length=50, default='')
    pre_requisites_3 = models.CharField(max_length=50, default='')
    learning_outcome_1 = models.CharField(max_length=100, default='')
    learning_outcome_2 = models.CharField(max_length=100, default='')
    learning_outcome_3 = models.CharField(max_length=100, default='')
    learning_outcome_4 = models.CharField(max_length=100, default='')
    learning_outcome_5 = models.CharField(max_length=100, default='')
    learning_outcome_6 = models.CharField(max_length=100, default='')
    description = RichTextUploadingField()

    outside_student = models.IntegerField(default=0)
    venue = models.CharField(max_length=50)
    resource_person = models.CharField(max_length=110)
    resource_person_pic = models.FileField(default='')
    resource_person_data = RichTextUploadingField()

    registered_student = models.IntegerField(default=0)
    registration_open = models.BooleanField(default=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.PROTECT)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = get_unique_slug(self, self.c_o_e, self.event_date)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.slug


class DataList(models.Model):
    place = models.CharField(max_length=50)
    number = models.IntegerField()

    def __str__(self):
        return self.place

event/forms.py
from datetime import date

from ckeditor_uploader.widgets import CKEditorUploadingWidget
from django import forms

from .models import EventRecord

EVENTS = [('workshop', 'Workshop'), ('seminar', 'Seminar'), ('competition', 'Competition'), ('training', 'Training'),
          ('guest-lecture', 'Guest Lecture')]
BRANCHES = [('CSE', 'CSE'), ('IT', 'IT'), ('EC', 'EC'), ('ME', 'ME'), ('EN', 'EN'),
            ('CE', 'CE'), ('MCA', 'MCA'), ('OTHER', 'OTHER')]
YEAR = [('1st Year', '1st Year'), ('2nd Year', '2nd Year'), ('3rd Year', '3rd Year'), ('4th Year', '4th Year')]
CHOICE = [(1, 'YES'), (0, 'NO')]
CENTER_OF_EXCELLENCE = [('SDA', 'Structural Design And Analysis'),
                        ('NW', 'Cisco Networking Academy'),
                        ('TIES', 'Texas Instruments Embedded System Lab'),
                        ('SMC', 'SMC India Pvt Ltd.'),
                        ('IARTC', 'Industrial Automation Research And Training Centre - IARTC'),
                        ('VLSI', 'VLSI Design'),
                        ('BIGD', 'Big Data Analytics'),
                        ('MobApp', 'Mobile Application Development'),
                        ('SWD', 'Center For Enterprise Software Development'),
                        ('TST', 'Testing'),
                        ('NI', 'ABES-NI Innovation Centre')]
DURATION_STRING = [('Hour', 'Hour'), ('Hours', 'Hours'), ('Day', 'Day'), ('Days', 'Days'), ('Week', 'Week'),
                   ('Weeks', 'Weeks'), ('Month', 'Month'), ('Months', 'Months')]


class EventForm(forms.ModelForm):
    type = forms.CharField(widget=forms.Select(
        choices=EVENTS, attrs={'class': 'form-control'}), required=True)
    c_o_e = forms.CharField(widget=forms.Select(
        choices=CENTER_OF_EXCELLENCE, attrs={'class': 'form-control'}), required=True)

    event_name = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Event Name'}), required=True, max_length=100)
    event_pic = forms.FileField(widget=forms.ClearableFileInput(
        attrs={'class': 'custom-file-input', 'style': "opacity:1"}), required=True)
    fees = forms.FloatField(widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Fees'}), min_value=0, max_value=10000, required=True)
    registration_start = forms.DateField(widget=forms.DateInput(
        attrs={'type': 'date', 'class': 'form-control'}))
    registration_end = forms.DateField(widget=forms.DateInput(
        attrs={'type': 'date', 'class': 'form-control'}))
    event_date = forms.DateField(widget=forms.DateInput(
        attrs={'type': 'date', 'class': 'form-control'}))
    duration_number = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Durations'}), required=True, max_length=5)
    duration_string = forms.CharField(widget=forms.Select(
        choices=DURATION_STRING, attrs={'class': 'form-control'}), required=True)
    eligible_branches = forms.CharField(widget=forms.CheckboxSelectMultiple(
        choices=BRANCHES, attrs={'class': 'form-check-inline'}), required=True)
    eligible_year = forms.CharField(widget=forms.CheckboxSelectMultiple(
        choices=YEAR, attrs={'class': 'form-check-inline'}), required=True)

    pre_requisites_1 = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Pre Requisites'}), required=True, max_length=50)
    pre_requisites_2 = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Pre Requisites'}), required=True, max_length=50)
    pre_requisites_3 = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Pre Requisites'}), required=True, max_length=50)
    learning_outcome_1 = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Learning Outcome'}), required=False, max_length=100)
    learning_outcome_2 = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Learning Outcome'}), required=False, max_length=100)
    learning_outcome_3 = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Learning Outcome'}), required=False, max_length=100)
    learning_outcome_4 = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Learning Outcome'}), required=False, max_length=100)
    learning_outcome_5 = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Learning Outcome'}), required=False, max_length=100)
    learning_outcome_6 = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Learning Outcome'}), required=False, max_length=100)
    description = forms.CharField(widget=CKEditorUploadingWidget())

    outside_student = forms.IntegerField(widget=forms.RadioSelect(
        choices=CHOICE, attrs={'class': 'form-check-inline'}), required=True)
    venue = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Venue'}), required=True, max_length=50)
    resource_person = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Resource Person'}), required=True, max_length=100)
    resource_person_data = forms.CharField(widget=CKEditorUploadingWidget())
    resource_person_pic = forms.FileField(widget=forms.ClearableFileInput(
        attrs={'class': 'custom-file-input', 'style': "opacity:1"}), required=True)

    class Meta:
        model = EventRecord
        fields = ['event_name', 'description', 'duration_number', 'resource_person', 'resource_person_data', 'venue',
                  'fees', 'registration_start', 'registration_end', 'event_date', 'type', 'c_o_e', 'duration_string',
                  'eligible_branches', 'outside_student', 'pre_requisites_1', 'pre_requisites_2', 'pre_requisites_3',
                  'learning_outcome_1', 'learning_outcome_2', 'learning_outcome_3', 'learning_outcome_4',
                  'learning_outcome_5', 'learning_outcome_6', 'resource_person_pic', 'event_pic', 'eligible_year']

    def clean_registration_start(self):
        try:
            registration_start = self.cleaned_data['registration_start']
            if True or registration_start.strftime('%Y-%m-%d') >= date.today().strftime('%Y-%m-%d'):
                return registration_start
            raise forms.ValidationError("Invalid Start Date")
        except Exception:
            raise forms.ValidationError("Invalid Start Date")

    def clean_registration_end(self):
        try:
            registration_start = self.cleaned_data['registration_start']
            registration_end = self.cleaned_data['registration_end']
            if registration_start <= registration_end:
                return registration_end
            raise forms.ValidationError("Invalid End Date")
        except Exception:
            raise forms.ValidationError("Invalid End Date")

    def clean_event_date(self):
        try:
            registration_start = self.cleaned_data['registration_start']
            event_date = self.cleaned_data['event_date']
            if registration_start <= event_date:
                return event_date
            raise forms.ValidationError("Invalid Event Date")
        except Exception:
            raise forms.ValidationError("Invalid Event Date")

event/views.py
from datetime import date

from django.contrib import messages
from django.core.exceptions import PermissionDenied, ObjectDoesNotExist
from django.shortcuts import render, redirect
from django.views.generic import TemplateView

from registration.models import RegistrationRecord
from .forms import EventForm
from .models import EventRecord


# Create your views here.
class EventListView(TemplateView):
    template_name = 'event-list.html'

    def get(self, request, *args, **kwargs):
        request.session['head_name'] = 'event'
        event_list = EventRecord.objects.all().order_by('-event_date')
        return render(request, self.template_name, {'event_list': event_list})


# noinspection PyBroadException
class EventDetail(TemplateView):
    template_name = 'event_detail.html'

    def get(self, request, *args, **kwargs):
        try:
            owner = False
            registered = True
            obj = EventRecord.objects.get(slug=kwargs['slug'])
            if obj.user == request.user or request.user.is_superuser:
                owner = True
            else:
                try:
                    RegistrationRecord.objects.get(user=request.user, event=obj)
                except Exception:
                    registered = False
            return render(request, self.template_name,
                          {'obj': obj, 'owner': owner, 'registered': registered, 'now': date.today()})
        except ObjectDoesNotExist:
            messages.error(request, 'Event Not found')
            return redirect('home')


# noinspection PyBroadException
class AddEvent(TemplateView):
    template_name = 'add_update_event.html'

    def get(self, request, *args, **kwargs):
        try:
            if request.user.is_staff:
                form = EventForm()
            else:
                raise PermissionDenied
            return render(request, self.template_name, {'form': form})
        except PermissionDenied:
            messages.error(request, 'Permission Denied')
            return redirect('home')

    def post(self, request):
        if True:
            if request.user.is_staff:
                form = EventForm(request.POST, request.FILES)
                if form.is_valid():
                    temp = form.save(commit=False)
                    temp.user = request.user
                    form.save()
                    messages.success(request, 'Event Added')
                    return redirect('event:event_detail', slug=temp.slug)
                else:
                    messages.error(request, 'Invalid Input')
            else:
                raise PermissionDenied
            return render(request, self.template_name, {'form': form})
        # except Exception:
        #     messages.error(request, 'Permission Denied')
        #     return redirect('home')


# noinspection PyBroadException
class UpdateEvent(TemplateView):
    template_name = 'add_update_event.html'

    def get(self, request, *args, **kwargs):
        try:
            if request.user.is_staff or request.user.is_superuser:
                obj = EventRecord.objects.get(slug=kwargs['slug'])
                if obj.user == request.user or request.user.is_superuser:
                    form = EventForm(instance=obj)
                else:
                    raise PermissionDenied
            else:
                raise PermissionDenied
            return render(request, self.template_name, {'form': form})
        except Exception:
            messages.error(request, 'Permission Denied')
            return redirect('home')

    def post(self, request, **kwargs):
        try:
            obj = EventRecord.objects.get(slug=kwargs['slug'])
            f = obj.fees
            if obj.user == request.user or request.user.is_superuser:
                form = EventForm(request.POST, request.FILES, instance=obj)
                if form.is_valid():
                    fee = form.cleaned_data['fees']
                    diff = fee - f
                    if diff != 0:
                        student_list = RegistrationRecord.objects.filter(event=obj)
                        for student in student_list:
                            student.balance += diff
                            student.save(update_fields=['balance'])
                    form.save()
                    messages.success(request, 'Event Updated')
                    return redirect('event:event_detail', kwargs['slug'])
                else:
                    messages.error(request, 'Invalid Input')
                return render(request, self.template_name, {'form': form})
            else:
                raise PermissionDenied
        except Exception:
            messages.error(request, 'Permission Denied')
            return redirect('home')


class DeleteEvent(TemplateView):

    def get(self, request, *args, **kwargs):
        try:
            obj = EventRecord.objects.get(slug=kwargs['slug'])
            if str(obj.timestamp) == kwargs['timestamp'] and (obj.user == request.user or request.user.is_superuser):
                if obj.registered_student > 0:
                    raise PermissionDenied('Student Registered, You can not delete this event.')
                obj.delete()
                messages.success(request, 'Event Deleted')
            else:
                raise PermissionDenied('Permission Denied')
        except ObjectDoesNotExist:
            messages.error(request, 'Event Not found')
            return redirect('home')
        except PermissionDenied as msg:
            messages.warning(request, msg)
            return redirect('account:consolidated_view_all')

event/templates/add_update_event.html
{% extends "base.html" %}{% load staticfiles %}{% block head_title %}Add Event | {{ block.super }}{% endblock %}
{% block content %}
    <div class="p-3 pt-4 bg-white rounded shadow-sm">
        <h2>Add/Update Event</h2>
        <form enctype="multipart/form-data" action="" method="post" class="px-md-2">{% csrf_token %}
            <h3>Event Information*</h3>
            <div class="form-row px-md-5">
                {{ form.media }}
                <div class="pb-4 col-md-4"><label>Select Event:</label>{{ form.type }}{{ form.type.errors }}</div>
                <div class="pb-4 col-md-4"><label>Centre of Excellence:</label>{{ form.c_o_e }}{{ form.c_o_e.errors }}</div>
                <div class="pb-4 col-md-4"><label>Fees:</label>{{ form.fees }}{{ form.fees.errors }}</div>
                <div class="pb-4 col-md-8"><label>Event name</label>{{ form.event_name }}{{ form.event_name.errors }}
                </div>
                <div class="col-md-4"><label>Duration</label>
                    <div class="row">
                        <div class="pb-4 col-md-7">{{ form.duration_number }}
                            <span style="color:red;">{{ form.duration_number.errors }}</span></div>
                        <div class="pb-4 col-md-5">{{ form.duration_string }}{{ form.duration_string.errors }}</div>
                    </div>
                </div>
                <div class="pb-4 col-md-4">
                    <label>Registration start</label>{{ form.registration_start }}{{ form.registration_start.errors }}
                </div>
                <div class="pb-4 col-md-4">
                    <label>Registration end</label>{{ form.registration_end }}{{ form.registration_end.errors }}
                </div>
                <div class="pb-4 col-md-4">
                    <label>Event Start</label>{{ form.event_date }}{{ form.event_date.errors }}
                </div>
                <div class="pb-4 col-md-12">Eligible branches{% for radio in form.eligible_branches %}
                    <div class="pl-sm-4 pl-2 form-check form-check-inline">{{ radio }}</div>
                {% endfor %}{{ form.eligible_branches.errors }}</div>
                <div class="pb-4 col-md-12">Eligible Year{% for radio in form.eligible_year %}
                    <div class="pl-sm-4 pl-2 form-check form-check-inline">{{ radio }}</div>
                {% endfor %}{{ form.eligible_year.errors }}</div>
                <div class="pb-4 col-md-12"><label>Outside students allowed</label>
                    {% for radio in form.outside_student %}
                        <div class="pl-sm-4 pl-2 form-check form-check-inline">{{ radio }}</div>
                    {% endfor %}{{ form.outside_student.errors }}</div>
                <div class="pb-4 col-md-8"><label>Venue:</label>{{ form.venue }}{{ form.venue.errors }}</div>
                <div class="pb-4 col-md-4"><label>Event logo: (100X100 svg file)</label>{{ form.event_pic }}{{ form.event_pic.errors }}</div>
                <div class="pb-4 col-md-4"><label>Learning Outcome 1:</label>{{ form.learning_outcome_1 }}{{ form.learning_outcome_1.errors }}</div>
                <div class="pb-4 col-md-4"><label>Learning Outcome 2:</label>{{ form.learning_outcome_2 }}{{ form.learning_outcome_2.errors }}</div>
                <div class="pb-4 col-md-4"><label>Learning Outcome 3:</label>{{ form.learning_outcome_3 }}{{ form.learning_outcome_3.errors }}</div>
                <div class="pb-4 col-md-4"><label>Learning Outcome 4:</label>{{ form.learning_outcome_4 }}{{ form.learning_outcome_4.errors }}</div>
                <div class="pb-4 col-md-4"><label>Learning Outcome 5:</label>{{ form.learning_outcome_5 }}{{ form.learning_outcome_5.errors }}</div>
                <div class="pb-4 col-md-4"><label>Learning Outcome 6:</label>{{ form.learning_outcome_6 }}{{ form.learning_outcome_6.errors }}</div>
                <div class="pb-4 col-md-4"><label>Pre-Requisites 1:</label>{{ form.pre_requisites_1 }}{{ form.pre_requisites_1.errors }}</div>
                <div class="pb-4 col-md-4"><label>Pre-Requisites 2:</label>{{ form.pre_requisites_2 }}{{ form.pre_requisites_2.errors }}</div>
                <div class="pb-4 col-md-4"><label>Pre-Requisites 3:</label>{{ form.pre_requisites_3 }}{{ form.pre_requisites_3.errors }}</div>
                <div class="pb-4 col-md-12"><label>Description</label>{{ form.description }}{{ form.description.errors }}</div>
                <div class="pb-4 col-md-7"><label>Resource person:</label>{{ form.resource_person }}{{ form.resource_person.errors }}</div>
                <div class="pb-4 col-md-5">
                    <label>Resource person Image: (500X500 image file)</label>{{ form.resource_person_pic }}{{ form.resource_person_pic.errors }}</div>
                <div class="pb-4 col-md-12"><label>Resource person data:</label>{{ form.resource_person_data }}{{ form.resource_person_data.errors }}</div>
{#            {{ form.as_p }}#}
            </div>
            <div class="px-md-5 pb-5 btn-toolbar">
                <button type="submit" class="px-5 m-2 btn btn-outline-primary">Submit</button>
                <button type="reset" class="px-4 m-2 btn btn-outline-danger">Reset</button>
            </div>
        </form>
    </div>{% endblock %}

event/templates/event-list.html
{% extends "base.html" %}{% load staticfiles %}{% block head_title %}Home | {{ block.super }}{% endblock %}
<main>{% block content %}</main>
    <div class="row" id="events" style="margin: 0; background-color: #1492E6">
        <div class="col-lg-6 order-lg-0" style="padding:0">
            <img src="{% static 'images/Asset 51.svg' %}" alt="logo" style="width: 60%"></div>
        <div class="col-lg-6 order-lg-1 align-self-lg-center px-md-5 px-3 pt-5 text-center">
            <h2 class="px-3" style="color:#ffffff;font-size: 2.4em">Enhance Your Knowledge<br>Shape Your Future </h2>
            <hr class="mb-3" style="width: 250px; border-top: 2px solid #ffffff">
            <h2 class="px-3" style="color:#FFFFFF;font-size: 2em">Summer Internship 2019</h2>
        </div>
    </div>
    <div class="row" style="margin: 0; background-color: #1492E6">
        <div class="col-lg-12 pb-3 px-3 text-center">
            <div class="card-deck my-4">{% for data in event_list %}
                <a class="card mb-4 card-custom {% if forloop.counter|divisibleby:2 %}odd{% else %}even{% endif %}" href="{% url 'event:event_detail' data.slug %}">
                    <div class="card-body d-flex align-items-center" style="margin: auto">{{ data.event_name }}<br>Branch: {{ data.eligible_branches }}
                    </div>
                </a>{% endfor %}
            </div>
        </div>
    </div>{% endblock %}

event/templates/event_detail.html
{% extends 'base.html' %}{% load staticfiles %}{% block head_title %}Event Detail | {{ block.super }}{% endblock %}
<main>{% block content %}</main>
    <div class="bg-blue pt-4" style="margin-top: -32px">
        <div class="container pt-md-4 text-md-left text-center">
            <div class="d-flex flex-md-row flex-column">
                <img src="/media/{{ obj.event_pic }}" alt="logo" class="mb-3" style="height: 100px; margin: auto; margin-top: 0">
                <div class="flex-md-grow-1 text-white px-3 mb-3">
                    <h1 class="mb-3">{{ obj.event_name }}</h1>{% if owner %}
                    <a class="btn btn-custom mb-4" style="border: 2px solid #ffffff; padding: .4rem 4rem;" href="{% url 'event:update_event' obj.slug %}">Update</a>{% elif registered %}
                    <button class="btn btn-custom mb-4" style="border: 2px solid #ffffff; padding: .4rem 4rem;" disabled>Already Registered</button>
                    {% else %}{% if now <= obj.registration_end and obj.registration_open %}
                        <a class="btn btn-custom mb-4" style="border: 2px solid #ffffff; padding: .4rem 4rem;" onclick='return confirm("Are you sure to register in {{ obj.event_name }}")' href="{% url 'registration:register_event' obj %}">Register Now</a>{% else %}
                        <button class="btn btn-custom mb-4" style="border: 2px solid #ffffff; padding: .4rem 4rem;" disabled>Registration Closed</button>{% endif %}{% endif %}
                    <p>Registration last Date: {{ obj.registration_end }}</p>
                </div>
                <div class="text-white mb-3 col-lg-3" style="margin: auto">
                    <p>Fee: <span style="font-size: 40px">₹ {{ obj.fees }}</span></p>
                    <p>Event Date: {{ obj.event_date }}</p>
                </div>
            </div>
            <div id="demo" class="collapse">
                <div class="px-3 px-md-5 text-white">
                    {# <p class="mb-4">Learn most demanding language with python and data visualization</p>#}
                    <ul>
                        <li class="mb-2">Registration Start: {{ obj.registration_start }}</li>
                        <li class="mb-2">Eligible Branch: {{ obj.eligible_branches }}</li>
                        <li class="mb-2">Eligible Year: {{ obj.eligible_year }}</li>
                        <li class="mb-2">Outside of ABES Engineering College student
                            {% if obj.outside_student == 1 %}Allowed{% else %}Not Allowed{% endif %}</li>
                        <li class="mb-2">Venue: {{ obj.venue }}</li>
                    </ul>
                    <p>Duration: {{ obj.duration_number }} {{ obj.duration_string }}</p>
                </div>
            </div>
        </div>
        <div style="text-align: center;">
            <button class="btn text-white" data-toggle="collapse" data-target="#demo" style="border-radius: 50%!important;height: 95px;font-size: small; margin-bottom: -45px; background-color: rgba(0, 183, 209, 1); background-image: linear-gradient(rgba(0, 183, 209, 1), rgba(20, 146, 230, 1));">Show More<br><span style="font-size: x-large; line-height: 0;margin-bottom: -3px">&#8744;</span>
            </button>
        </div>
    </div>
    <div class="container mt-5 p-4">
        <div class="d-flex justify-content-md-between flex-md-row flex-column">
            <div class="text-center align-self-center pb-3"><h2>Pre-Requisites</h2>
                <hr style="width: 110px; border: 1px solid rgba(0,0,0,0.62);">
                <div style="border-left: 2px solid grey;border-right: 2px solid grey;border-radius: 50rem; width: 432px;padding: 20px 0">
                    <p>{{ obj.pre_requisites_1 }}</p>
                    <p>{{ obj.pre_requisites_2 }}</p>
                    <p>{{ obj.pre_requisites_3 }}</p></div>
            </div>
            <div class="text-center align-self-center pb-3"><h2>Learning OutCome</h2>
                <hr style="width: 110px; border: 1px solid rgba(0,0,0,0.62);">
                <div style="border-left: 2px solid grey;border-right: 2px solid grey;border-bottom: 2px solid grey; border-radius: 2rem; width: 350px; padding: 20px">
                    <p>{{ obj.learning_outcome_1 }}</p>
                    <p>{{ obj.learning_outcome_2 }}</p>
                    <p>{{ obj.learning_outcome_3 }}</p>
                    <p>{{ obj.learning_outcome_4 }}</p>
                    <p>{{ obj.learning_outcome_5 }}</p>
                    <p>{{ obj.learning_outcome_6 }}</p></div>
            </div>
        </div>
    </div>
    <div class="container text-center pb-5">
        <hr style="width: 70%; border-top: 4px solid #1492E6; border-radius: 50rem">
        <h2 class="mt-5">Course Content</h2>
        <hr style="width: 110px; border: 1px solid rgba(0,0,0,0.62);">
        <div class="p-4 p-md-5 mt-5" style="border: 2px solid grey; border-radius: 2rem; text-align: initial">
            {{ obj.description|safe }}
        </div>
    </div>
    <div class="container text-center pb-3">
        <hr style="width: 70%; border-top: 4px solid #1492E6; border-radius: 50rem">
        <h2 class="mt-5">About The Instructor</h2>
        <hr style="width: 110px; border: 1px solid rgba(0,0,0,0.62);">
        <div class="p-4" style="text-align: initial">
            <h2>{{ obj.resource_person }}</h2>
            {{ obj.resource_person_data|safe }}
        </div>
    </div>{% endblock content %}