account/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from .views import superuser, del_user, edit_user
from .views import logout, Login, Signup, ForgetPassword, Activate, ConsolidatedView

urlpatterns = [
    path('login', Login.as_view(), name='login'),
    path('signup', Signup.as_view(), name='signup'),
    path('logout', login_required(logout), name='logout'),
    path('activate/<uidb64>/<token>/', Activate.as_view(), name='activate'),
    path('forget-password/<uidb64>/<token>', ForgetPassword.as_view(), name='forget_password'),

    path('superuser/', login_required(superuser), name='superuser'),
    path('edit_user/<username>', login_required(edit_user), name='edit_user'),
    path('delete-user/<username>', login_required(del_user), name='delete_user'),

    path('consolidated-view-all', login_required(ConsolidatedView.as_view()), name='consolidated_view_all'),
    path('consolidated-view-c_o_e/<c_o_e>', login_required(ConsolidatedView.as_view()), name='consolidated_c_o_e'),
    path('consolidated-view-username/<username>', login_required(ConsolidatedView.as_view()), name='consolidated_username'),
]

cbseevents/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path

from .views import *

admin.site.site_header = settings.ADMIN_SITE_HEADER
admin.site.site_title = settings.ADMIN_SITE_TITLE

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('event/', include(('event.urls', 'event'), namespace='event')),
    path('account/', include(('account.urls', 'account'), namespace='account')),
    path('registration/', include(('registration.urls', 'registration'), namespace='registration')),

    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),

    # path('set', set_user),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

event/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from .views import AddEvent, EventDetail, UpdateEvent, DeleteEvent, EventListView

urlpatterns = [
    path('', EventListView.as_view(), name='event_list'),
    path('add-event', login_required(AddEvent.as_view()), name='add_event'),
    path('<slug>/event-detail', EventDetail.as_view(), name='event_detail'),
    path('<slug>/update-event', login_required(UpdateEvent.as_view()), name='update_event'),
    path('<slug>/delete/<timestamp>', login_required(DeleteEvent.as_view()), name='delete_event'),
]

templates/base.html
<!doctype html>{% load static from staticfiles %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block head_title %}CBSE Event{% endblock head_title %}</title>
    <style>#loading {position: fixed;width: 100%;height: 100%;background: #fff url("{% static 'images/Bulb.gif' %}") no-repeat center;z-index: 99999;}</style>
    <link rel="shortcut icon" href="{% static 'favicon.png' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Varela+Round"/>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% block css %}{% endblock css %}
</head>
<body onload="preloader()" style="min-height: 100%;">
<div id="loading" about="preloader"></div>
<nav class="navbar navbar-expand-lg navbar-light fixed-top" style="padding: 0;box-shadow: 0 0.15rem 0.1rem 0 rgba(0,0,0,.05);background-color: white">
    <a class="navbar-brand p-0" href="{% url 'home' %}"><img src="{% static 'images/cbselogo.png' %}" style="width: 200px; padding-left: 1rem" alt="CBSE"></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span></button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <div class="flex-grow-1 flex-column ">
            <h2 class="text-white py-2 text-center" style="font-size: 20px; background-color: maroon">Centre for Building Skills & Employability</h2>
            <div class="my-3 my-md-3 mr-md-5 align-items-md-center text-center text-md-right">
                <a class="py-1 mr-md-5 ml-2 custom-a {% if request.session.head_name == 'home' %}under-line{% endif %}" href="{% url 'home' %}">Home</a>
                <a class="py-1 mr-md-5 ml-2 custom-a {% if request.session.head_name == 'event' %}under-line{% endif %}" href="{% url 'event:event_list' %}">Event</a>
                <a class="py-1 mr-md-5 ml-2 custom-a {% if request.session.head_name == 'news' %}under-line{% endif %}" href="{% url 'home' %}">News</a>
                {% if user.is_authenticated %}
                    {% if user.is_superuser %}
                        <a class="py-1 mr-md-5 ml-2 custom-a {% if request.session.head_name == 'manage_user' %}under-line{% endif %}" href="{% url 'account:superuser' %}">Manage User</a>
                        <a class="py-1 mr-md-5 ml-2 custom-a {% if request.session.head_name == 'generate_report' %}under-line{% endif %}" href="">Generate Report</a>
                    {% elif user.is_staff %}
                        <a class="py-1 mr-md-5 ml-2 custom-a {% if request.session.head_name == 'add_event' %}under-line{% endif %}" href="{% url 'event:add_event' %}">Add Event</a>{% endif %}
                    <a class="py-1 mr-md-5 ml-2 custom-a {% if request.session.head_name == 'profile' %}under-line{% endif %}" href="{% url 'account:consolidated_view_all' %}">Consolidated View</a>
                    <a class="py-1 mr-md-5 ml-2 custom-a" href="{% url 'account:logout' %}">Logout</a>
                {% else %}
                    <a class="py-1 mr-md-5 ml-2 custom-a {% if request.session.head_name == 'login' %}under-line{% endif %}" href="{% url 'account:login' %}">Login</a>
                    <a class="py-1 ml-2 custom-a {% if request.session.head_name == 'signup' %}under-line{% endif %}" href="{% url 'account:signup' %}">Signup</a>
                {% endif %}
            </div>
        </div>
    </div>
</nav>
<div class="pt-2 mt-2 pt-md-5 mt-md-5">{% for m in messages %}
    <!-- Alert -->
    <div class="alert alert-dismissible fade show container fit-text mt-4 {% if m.tags == 'success' %}alert-success{% elif m.tags == 'warning' %}alert-warning{% elif m.tags == 'info' %}alert-info{% else %}alert-danger{% endif %}" role="alert">{{ m }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span></button>
    </div>{% endfor %}
    <!-- - - - - - - - - - START - - - - - - - - - - - -->{% block content %}{% endblock content %}<!-- - - - - - - - - - END - - - - - - - - - - - - -->
</div>
<!-- Footer -->
<div style="background-color: rgb(112,112,112);width: 100%; margin-top: auto">
    <footer class="py-4 text-white container text-center">
        <hr style="border-top: 2px solid #ffffff">
        <span style="font-weight: 200;">Copyright &copy; 2019 - All Right Reserved. Website Designed & Developed by ASCII Team</span>
    </footer>
</div>
<!-- Preloader Scripts -->
<script>
    function preloader() {
        document.getElementById('loading').style.display = 'none';
    }</script>
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
<script src="{% static 'js/search.js' %}"></script>
{% block script %}{% endblock script %}
</body>
</html>

templates/index.html
{% extends "base.html" %}{% load staticfiles %}{% block head_title %}Home | {{ block.super }}{% endblock %}
{% block content %}
    <div class="row" style="margin: 1rem 0 0 0">
        <div class="col-lg-6 order-lg-1 pb-5">
            <img src="{% static 'images/Asset 50.svg' %}" alt="logo" style="width: 100%"></div>
        <div class="col-lg-6 order-lg-0 align-self-lg-center px-lg-5 pb-5 text-center">
            <h1 class="px-4" style="color:#414141;font-size: 3rem;">Summer Internship 2019</h1>
            <hr style="width: 70px; border: 1px solid rgba(0,0,0,0.23);">
            <p class="px-3" style="font-size: 24px; color:#777777;">A gateway to technical Advancement</p>
            <div class="px-3 pl-lg-5" style="text-align: left;">
                <li style="font-size: small;list-style-type: circle;">Venue: CBSE Department, Ground Floor, KC Building, ABES Engineering College</li>
                <li style="font-size: small;list-style-type: circle;">Limited Number of seats in each course: 15</li>
            </div>
            <a class="btn btn-custom mt-4 px-lg-5 py-3" href="#events" style="border: 0; font-size: 24px; box-shadow: 5px 5px 10px rgba(0,0,0,.50)!important;">Registration Open</a><br><br>
            <a href="https://forms.gle/drMJmH39N9zxEjt17">TCS Placement Preparation Program</a>
        </div>
    </div>
    <div class="row mt-lg-3" id="events" style="margin: 0; background-color: #1492E6">
        <div class="col-lg-6 order-lg-0" style="padding:0">
            <img src="{% static 'images/Asset 51.svg' %}" alt="logo" style="width: 60%"></div>
        <div class="col-lg-6 order-lg-1 align-self-lg-center px-md-5 px-3 pt-5 text-center">
            <h2 class="px-3" style="color:#ffffff;font-size: 2.4em">Enhance Your Knowledge<br>Shape Your Future </h2>
            <hr class="mb-3" style="width: 250px; border-top: 2px solid #ffffff">
            <h2 class="px-3" style="color:#FFFFFF;font-size: 2em">Internship 2020</h2>
        </div>
    </div>
    <div class="row" style="margin: 0; background-color: #1492E6">
        <div class="col-lg-12 pb-3 px-3 text-center">
            <div class="card-deck my-4">{% for data in event_list %}
                <a class="card mb-4 card-custom {% if forloop.counter|divisibleby:2 %}odd{% else %}even{% endif %}" href="{% url 'event:event_detail' data.slug %}">
                    <div class="card-body d-flex align-items-center" style="margin: auto">{{ data.event_name }}<br>Branch: {{ data.eligible_branches }}
                    </div>
                </a>{% endfor %}
            </div>
        </div>
        <div class="col-lg-12 pb-5 text-center">
            <a class="btn btn-custom" href="{% url 'event:event_list' %}" style="border: 3px solid #ffffff; padding: .4rem 4rem;">Explore More</a>
        </div>
    </div>
    {#        <div style="background-color: rgb(0,183,209)">#}
    {#        <div class="container pt-5 pb-4">#}
    {#            <h1 style="color: #FFFFFF; font-weight: 100;" class="text-center pb-4">News</h1>#}
    {#            <p style="border-left: 0.1rem solid #ffffff; font-size: 20px" class="px-5 mb-5 text-white">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Culpa excepturi fugiat ipsam iusto magnam natus provident, temporibus vitae? Consectetur consequuntur delectus dolor, ex hic labore optio perferendis quae quidem quisquam!</p>#}
    {#            <p style="border-right: 0.1rem solid #ffffff; font-size: 20px" class="px-5 text-white">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Culpa excepturi fugiat ipsam iusto magnam natus provident, temporibus vitae? Consectetur consequuntur delectus dolor, ex hic labore optio perferendis quae quidem quisquam!</p>#}
    {#            <div style="color: #FFFFFF; font-size: 90px;" class="text-center">...</div>#}
    {#        </div>#}
    {#    </div>#}
{% endblock %}